<a href="https://colab.research.google.com/github/Bhanu9900/All-files/blob/main/CIE_Test_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/salary_Data.csv")
print(df)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0


In [ ]:
df.head(4)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0

In [ ]:
df.tail(5)

YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [ ]:
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [ ]:
df.shape

(30, 2)

In [ ]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [ ]:
df.sum()

YearsExperience        159.4
Salary             2280090.0
dtype: float64

In [ ]:
df.min()

YearsExperience        1.1
Salary             37731.0
dtype: float64

In [ ]:
df.max()

YearsExperience        10.5
Salary             122391.0
dtype: float64

In [ ]:
df.mean()

YearsExperience        5.313333
Salary             76003.000000
dtype: float64

In [ ]:
Ddf.median()

YearsExperience        4.7
Salary             65237.0
dtype: float64

In [ ]:
df.mode()

YearsExperience    Salary
0               3.2   37731.0
1               4.0   39343.0
2               NaN   39891.0
3               NaN   43525.0
4               NaN   46205.0
5               NaN   54445.0
6               NaN   55794.0
7               NaN   56642.0
8               NaN   56957.0
9               NaN   57081.0
10              NaN   57189.0
11              NaN   60150.0
12              NaN   61111.0
13              NaN   63218.0
14              NaN   64445.0
15              NaN   66029.0
16              NaN   67938.0
17              NaN   81363.0
18              NaN   83088.0
19              NaN   91738.0
20              NaN   93940.0
21              NaN   98273.0
22              NaN  101302.0
23              NaN  105582.0
24              NaN  109431.0
25              NaN  112635.0
26              NaN  113812.0
27              NaN  116969.0
28              NaN  121872.0
29              NaN  122391.0

In [ ]:
#Linear Regression
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
df=pd.read_csv("/content/salary_Data.csv")
X = df[['YearsExperience']]
y = df['Salary']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared Error:",mse)
print("R2 Score:",r2)

Mean Squared Error: 7.058607893785836e-23
R2 Score: 1.0


In [ ]:
#Multiple Linear Regression
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
df=pd.read_csv("/content/salary_Data.csv")
X = df[['YearsExperience']]
y = df['Salary']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared Error:",mse)
print("Coefficients:",model.coef_)
print("Intercept:",model.intercept_)

Mean Squared Error: 7.058607893785836e-23
Coefficients: [1.]
Intercept: -1.4551915228366852e-11


In [ ]:
#Ploynomial Regression
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
df = pd.read_csv('/content/salary_Data.csv')
X = df[['YearsExperience']]
y = df['Salary']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)
model = LinearRegression()
model.fit(X_train_poly, y_train)
y_pred=model.predict(X_test_poly)
mse = mean_squared_error(y_test, y_pred)
print(f'MSE:{mse:.2f}')

MSE:52527916.37


In [ ]:
#Binary Classification
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
df=pd.read_csv("/content/salary_Data.csv")
X = df[['YearsExperience']]
y = df['Salary']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("R2 Score:", r2)

Mean Squared Error: 7.058607893785836e-23
R2 Score: 1.0


In [6]:
#Multi label classification
import pandas as pd
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, multilabel_confusion_matrix
X,y = make_multilabel_classification(n_samples=100, n_features=20, n_classes=5, n_labels=3, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = MultiOutputClassifier(LogisticRegression(max_iter=1000))
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(multilabel_confusion_matrix(y_test, y_pred))


Accuracy: 0.2
Confusion Matrix:
[[[ 8  4]
  [ 4  4]]

 [[ 2  5]
  [ 3 10]]

 [[ 6  2]
  [ 3  9]]

 [[ 5  1]
  [ 3 11]]

 [[ 9  5]
  [ 4  2]]]


In [ ]:
#Multi Class Classification
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
df = pd.read_csv('/content/salary_Data.csv')
X = df.drop('Salary', axis=1)
df['YearsExperienceCategory'] = pd.cut(df['YearsExperience'], bins=[0, 5, 10, 15, 20], labels=[1, 2, 3, 4])
y = df['YearsExperienceCategory']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")

Accuracy: 1.0
Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         3

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6

Confusion Matrix:


In [ ]:
#Imbalanced Classification
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
df = pd.read_csv('/content/salary_Data.csv')
X = df.drop('YearsExperience', axis=1)
y = df['Salary']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
class_weights = {i: len(y_train) / (len(y_train[y_train == i]) * len(np.unique(y_train))) for i in np.unique(y_train)}
model = LogisticRegression(class_weight=class_weights)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.0
Confusion Matrix:
[[0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]
